# Generated by Django 4.2.27 on 2026-02-03 17:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='admin', max_length=50, verbose_name='설정 키')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '관리자 환경 설정',
                'verbose_name_plural': '관리자 설정',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, verbose_name='사용자')),
                ('action', models.CharField(max_length=50, verbose_name='작업')),
                ('target', models.CharField(max_length=200, verbose_name='대상')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='일시')),
                ('details', models.TextField(blank=True, verbose_name='상세 내용')),
            ],
            options={
                'verbose_name': '감사 로그',
                'verbose_name_plural': '시스템 감사',
            },
        ),
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='작성자')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
            ],
            options={
                'verbose_name': '커뮤니티 게시글',
                'verbose_name_plural': '커뮤니티 관리',
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='질문 내용')),
                ('answer', models.TextField(blank=True, verbose_name='AI 답변')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='접수일')),
            ],
            options={
                'verbose_name': 'AI 상담 내역',
                'verbose_name_plural': 'AI 상담 로그',
            },
        ),
        migrations.CreateModel(
            name='ForecastRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_date', models.DateTimeField(auto_now_add=True, verbose_name='실행 일시')),
                ('model_name', models.CharField(default='Prophet-Ensemble', max_length=100, verbose_name='사용 모델')),
                ('status', models.CharField(default='SUCCESS', max_length=20, verbose_name='상태')),
                ('accuracy_metrics', models.JSONField(default=dict, verbose_name='정확도 지표 (MAPE 등)')),
            ],
            options={
                'verbose_name': '예측 모델 실행 이력',
                'verbose_name_plural': 'AI 모델 관리',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='General', max_length=50, verbose_name='카테고리')),
                ('item_name', models.CharField(max_length=100, verbose_name='상품명')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='상품코드')),
                ('current_stock', models.IntegerField(verbose_name='현재 재고')),
                ('optimal_stock', models.IntegerField(verbose_name='적정 재고')),
                ('status', models.CharField(choices=[('GOOD', '적정'), ('LOW', '부족'), ('OVER', '과잉')], default='GOOD', max_length=50, verbose_name='재고 상태')),
                ('cost', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='매입 단가')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='판매 단가')),
            ],
            options={
                'verbose_name': '상품/자재',
                'verbose_name_plural': '상품 및 재고 관리',
            },
        ),
        migrations.CreateModel(
            name='LocalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='행사명')),
                ('date', models.DateField(verbose_name='일시')),
                ('impact_level', models.CharField(max_length=50, verbose_name='영향도')),
            ],
            options={
                'verbose_name': '지역 행사 정보',
                'verbose_name_plural': '지역 행사 및 이벤트',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='지점명')),
                ('master_key', models.CharField(max_length=50, unique=True, verbose_name='액세스 키')),
                ('is_approved', models.BooleanField(default=True, verbose_name='승인 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
            ],
            options={
                'verbose_name': '지점/사용자',
                'verbose_name_plural': '사용자 및 권한',
            },
        ),
        migrations.CreateModel(
            name='OwnerSentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='기록일')),
                ('mood_score', models.IntegerField(default=5, verbose_name='기분 점수')),
                ('cheer_message', models.TextField(verbose_name='응원 메시지')),
            ],
            options={
                'verbose_name': '점주 심리 상태',
                'verbose_name_plural': '점주 심리 로그',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='거래처명')),
                ('type', models.CharField(choices=[('CUSTOMER', '고객'), ('SUPPLIER', '공급사'), ('BOTH', '모두')], default='CUSTOMER', max_length=20, verbose_name='구분')),
                ('contact_info', models.TextField(blank=True, verbose_name='연락처/비고')),
                ('balance', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='미수/미지급금')),
            ],
            options={
                'verbose_name': '거래처',
                'verbose_name_plural': '거래처 관리',
            },
        ),
        migrations.CreateModel(
            name='PosRawSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='수신 일시')),
                ('payload', models.JSONField(verbose_name='원본 데이터')),
                ('status', models.CharField(choices=[('RECEIVED', '수신됨'), ('PROCESSED', '처리완료'), ('FAILED', '처리실패')], default='RECEIVED', max_length=20, verbose_name='처리 상태')),
                ('error_log', models.TextField(blank=True, verbose_name='에러 로그')),
            ],
            options={
                'verbose_name': 'POS 원천 데이터',
                'verbose_name_plural': 'POS 수신 로그',
            },
        ),
        migrations.CreateModel(
            name='TaxCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='세금 명칭')),
                ('rate', models.DecimalField(decimal_places=4, default=0.1, max_digits=5, verbose_name='세율 (0.1=10%)')),
            ],
            options={
                'verbose_name': '세금/과세 설정',
                'verbose_name_plural': '세금 관리',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='거래 일시')),
                ('type', models.CharField(choices=[('SALE', '매철'), ('PURCHASE', '매입'), ('REFUND', '반품/취소')], default='SALE', max_length=20, verbose_name='거래 유형')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='총 공급가액')),
                ('tax_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='총 세액')),
                ('final_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='최종 합계')),
                ('status', models.CharField(choices=[('PENDING', '대기'), ('CONFIRMED', '확정'), ('CANCELLED', '취소')], default='PENDING', max_length=20, verbose_name='진행 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='platform_ui.partner', verbose_name='거래처')),
                ('raw_pos_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='platform_ui.posrawsales', verbose_name='POS 연동 참조')),
            ],
            options={
                'verbose_name': '거래 내역',
                'verbose_name_plural': '거래 관리',
            },
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='날짜')),
                ('condition', models.CharField(max_length=50, verbose_name='기상 상태')),
                ('temperature', models.FloatField(verbose_name='기온')),
            ],
            options={
                'verbose_name': '날씨 정보',
                'verbose_name_plural': '날씨 데이터',
            },
        ),
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='수량')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='단가')),
                ('line_total', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='라인 합계')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platform_ui.inventory', verbose_name='상품')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='platform_ui.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='PosItemMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_code', models.CharField(max_length=100, unique=True, verbose_name='POS 상품코드')),
                ('internal_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platform_ui.inventory', verbose_name='내부 상품 매핑')),
            ],
            options={
                'verbose_name': 'POS 상품 매핑',
                'verbose_name_plural': '매핑 관리',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='수량')),
                ('status', models.CharField(choices=[('PENDING', '대기'), ('COMPLETED', '완료'), ('CANCELLED', '취소')], default='PENDING', max_length=20, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='접수 일시')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platform_ui.inventory', verbose_name='대상 품목')),
            ],
            options={
                'verbose_name': '수주/발주 요청',
                'verbose_name_plural': '수주/발주 관리',
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('IN', '입고'), ('OUT', '출고'), ('ADJ', '조정')], max_length=10, verbose_name='유형')),
                ('quantity', models.IntegerField(verbose_name='수량 (변동분)')),
                ('reason', models.CharField(max_length=200, verbose_name='사유')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='일시')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platform_ui.inventory', verbose_name='상품')),
                ('ref_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='platform_ui.transaction', verbose_name='관련 거래')),
            ],
            options={
                'verbose_name': '재고 수불부',
                'verbose_name_plural': '입출고 이력',
            },
        ),
        migrations.AddField(
            model_name='inventory',
            name='tax_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='platform_ui.taxcode', verbose_name='과세 구분'),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='배송원 성함')),
                ('vehicle_info', models.CharField(blank=True, max_length=100, null=True, verbose_name='차량 정보')),
                ('delivery_address', models.TextField(verbose_name='배송지')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='배정/예약 시간')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='완료 시간')),
                ('status', models.CharField(choices=[('PENDING', '배차 대기'), ('SCHEDULED', '배송 예약'), ('IN_TRANSIT', '배송 중'), ('DELIVERED', '배송 완료'), ('CANCELLED', '취소됨')], default='PENDING', max_length=20, verbose_name='배송 상태')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='platform_ui.order', verbose_name='연관 주문')),
            ],
            options={
                'verbose_name': '배송 관리',
                'verbose_name_plural': '배송/물류 관리',
            },
        ),
        migrations.CreateModel(
            name='DailySales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='날짜')),
                ('item_name', models.CharField(default='All', max_length=200, verbose_name='상품명/구분')),
                ('revenue', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='실매출')),
                ('predicted_revenue', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='예상매출')),
            ],
            options={
                'verbose_name': '일일 매출 집계',
                'verbose_name_plural': '매출 리포트',
                'unique_together': {('date', 'item_name')},
            },
        ),
    ]
