# Generated by Django 4.2.27 on 2026-02-04 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_ui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='branch_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='지점명'),
        ),
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('SALES', '가맹점수주'), ('PURCHASE', '공급사발주')], default='SALES', max_length=10, verbose_name='주문 유형'),
        ),
    ]
