# Generated by Django 6.0.1 on 2026-02-02 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_ui', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='admin', max_length=50, verbose_name='관리자 키')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
