# Generated by Django 4.2.27 on 2026-02-04 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_ui', '0002_order_branch_name_order_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inbound',
            fields=[
            ],
            options={
                'verbose_name': '입고 관리 (Inbound)',
                'verbose_name_plural': '입고 관리',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('platform_ui.inventorymovement',),
        ),
        migrations.CreateModel(
            name='Outbound',
            fields=[
            ],
            options={
                'verbose_name': '출고 관리 (Outbound)',
                'verbose_name_plural': '출고 관리',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('platform_ui.delivery',),
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
            ],
            options={
                'verbose_name': '발주 관리 (Purchase Order)',
                'verbose_name_plural': '발주 관리',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('platform_ui.order',),
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
            ],
            options={
                'verbose_name': '수주 관리 (Sales Order)',
                'verbose_name_plural': '수주 관리',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('platform_ui.order',),
        ),
    ]
