# Generated by Django 4.2.27 on 2026-02-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_ui', '0006_remove_adminconfig_master_key_dailysales_item_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminconfig',
            options={'verbose_name': '관리자 설정', 'verbose_name_plural': '관리자 설정 항목'},
        ),
        migrations.AlterModelOptions(
            name='communitypost',
            options={'verbose_name': '커뮤니티 게시글', 'verbose_name_plural': '커뮤니티 게시판'},
        ),
        migrations.AlterModelOptions(
            name='consultation',
            options={'verbose_name': 'AI 상담 내역', 'verbose_name_plural': 'AI 상담 로그'},
        ),
        migrations.AlterModelOptions(
            name='dailysales',
            options={'verbose_name': '일일 매출', 'verbose_name_plural': '일일 매출 목록'},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': '재고 항목', 'verbose_name_plural': '재고 관리 목록'},
        ),
        migrations.AlterModelOptions(
            name='localevent',
            options={'verbose_name': '지역 이벤트', 'verbose_name_plural': '지역 이벤트 목록'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': '지점 파트너', 'verbose_name_plural': '지점 관리 목록'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '수주/입고 내역', 'verbose_name_plural': '수주/입고 관리 목록'},
        ),
        migrations.AlterModelOptions(
            name='ownersentiment',
            options={'verbose_name': '점주 기분/심리', 'verbose_name_plural': '점주 심리 상태 목록'},
        ),
        migrations.AlterModelOptions(
            name='weather',
            options={'verbose_name': '날씨 정보', 'verbose_name_plural': '날씨 데이터 목록'},
        ),
        migrations.AddField(
            model_name='member',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='승인 상태'),
        ),
        migrations.AlterField(
            model_name='adminconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='작성일'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='접수일'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='status',
            field=models.CharField(choices=[('GOOD', '적정'), ('LOW', '부족'), ('OVER', '과잉')], default='GOOD', max_length=50, verbose_name='상태'),
        ),
        migrations.AlterField(
            model_name='member',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='등록일'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='주문 일시'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(verbose_name='수량'),
        ),
    ]
