# Generated by Django 4.2.27 on 2026-02-03 12:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('platform_ui', '0007_alter_adminconfig_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, verbose_name='사용자')),
                ('action', models.CharField(max_length=50, verbose_name='작업')),
                ('target', models.CharField(max_length=200, verbose_name='대상')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='일시')),
                ('details', models.TextField(blank=True, verbose_name='상세 내용')),
            ],
            options={
                'verbose_name': '감사 로그',
                'verbose_name_plural': '시스템 감사',
            },
        ),
        migrations.CreateModel(
            name='ForecastRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_date', models.DateTimeField(auto_now_add=True, verbose_name='실행 일시')),
                ('model_name', models.CharField(default='Prophet-Ensemble', max_length=100, verbose_name='사용 모델')),
                ('status', models.CharField(default='SUCCESS', max_length=20, verbose_name='상태')),
                ('accuracy_metrics', models.JSONField(default=dict, verbose_name='정확도 지표 (MAPE 등)')),
            ],
            options={
                'verbose_name': '예측 모델 실행 이력',
                'verbose_name_plural': 'AI 모델 관리',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='거래처명')),
                ('type', models.CharField(choices=[('CUSTOMER', '고객'), ('SUPPLIER', '공급사'), ('BOTH', '모두')], default='CUSTOMER', max_length=20, verbose_name='구분')),
                ('contact_info', models.TextField(blank=True, verbose_name='연락처/비고')),
                ('balance', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='미수/미지급금')),
            ],
            options={
                'verbose_name': '거래처',
                'verbose_name_plural': '거래처 관리',
            },
        ),
        migrations.CreateModel(
            name='PosRawSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='수신 일시')),
                ('payload', models.JSONField(verbose_name='원본 데이터')),
                ('status', models.CharField(choices=[('RECEIVED', '수신됨'), ('PROCESSED', '처리완료'), ('FAILED', '처리실패')], default='RECEIVED', max_length=20, verbose_name='처리 상태')),
                ('error_log', models.TextField(blank=True, verbose_name='에러 로그')),
            ],
            options={
                'verbose_name': 'POS 원천 데이터',
                'verbose_name_plural': 'POS 수신 로그',
            },
        ),
        migrations.CreateModel(
            name='TaxCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='세금 명칭')),
                ('rate', models.DecimalField(decimal_places=4, default=0.1, max_digits=5, verbose_name='세율 (0.1=10%)')),
            ],
            options={
                'verbose_name': '세금/과세 설정',
                'verbose_name_plural': '세금 관리',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='거래 일시')),
                ('type', models.CharField(choices=[('SALE', '매철'), ('PURCHASE', '매입'), ('REFUND', '반품/취소')], default='SALE', max_length=20, verbose_name='거래 유형')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='총 공급가액')),
                ('tax_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='총 세액')),
                ('final_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='최종 합계')),
                ('status', models.CharField(choices=[('PENDING', '대기'), ('CONFIRMED', '확정'), ('CANCELLED', '취소')], default='PENDING', max_length=20, verbose_name='진행 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='platform_ui.partner', verbose_name='거래처')),
                ('raw_pos_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='platform_ui.posrawsales', verbose_name='POS 연동 참조')),
            ],
            options={
                'verbose_name': '거래 내역',
                'verbose_name_plural': '거래 관리',
            },
        ),
        migrations.AlterModelOptions(
            name='adminconfig',
            options={},
        ),
        migrations.AlterModelOptions(
            name='communitypost',
            options={},
        ),
        migrations.AlterModelOptions(
            name='consultation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='dailysales',
            options={'verbose_name': '일일 매출 집계', 'verbose_name_plural': '매출 리포트'},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': '상품/자재', 'verbose_name_plural': '상품 및 재고 관리'},
        ),
        migrations.AlterModelOptions(
            name='localevent',
            options={},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': '지점/사용자', 'verbose_name_plural': '사용자 및 권한'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ownersentiment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='weather',
            options={},
        ),
        # Removed conflicting RemoveField operations for event_impact and weather_impact
        migrations.AddField(
            model_name='inventory',
            name='category',
            field=models.CharField(default='General', max_length=50, verbose_name='카테고리'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='상품코드'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='cost',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='매입 단가'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='판매 단가'),
        ),
        migrations.AlterField(
            model_name='adminconfig',
            name='key',
            field=models.CharField(default='admin', max_length=50),
        ),
        migrations.AlterField(
            model_name='adminconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='answer',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='question',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dailysales',
            name='item_name',
            field=models.CharField(default='All', max_length=200, verbose_name='상품명/구분'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='status',
            field=models.CharField(choices=[('GOOD', '적정'), ('LOW', '부족'), ('OVER', '과잉')], default='GOOD', max_length=50, verbose_name='재고 상태'),
        ),
        migrations.AlterField(
            model_name='localevent',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='localevent',
            name='impact_level',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='localevent',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='member',
            name='master_key',
            field=models.CharField(max_length=50, unique=True, verbose_name='액세스 키'),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=100, verbose_name='지점명'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', '대기'), ('COMPLETED', '완료'), ('CANCELLED', '취소')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='ownersentiment',
            name='cheer_message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ownersentiment',
            name='mood_score',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='weather',
            name='condition',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='weather',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='weather',
            name='temperature',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='수량')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='단가')),
                ('line_total', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='라인 합계')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platform_ui.inventory', verbose_name='상품')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='platform_ui.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='PosItemMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_code', models.CharField(max_length=100, unique=True, verbose_name='POS 상품코드')),
                ('internal_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platform_ui.inventory', verbose_name='내부 상품 매핑')),
            ],
            options={
                'verbose_name': 'POS 상품 매핑',
                'verbose_name_plural': '매핑 관리',
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('IN', '입고'), ('OUT', '출고'), ('ADJ', '조정')], max_length=10, verbose_name='유형')),
                ('quantity', models.IntegerField(verbose_name='수량 (변동분)')),
                ('reason', models.CharField(max_length=200, verbose_name='사유')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='일시')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platform_ui.inventory', verbose_name='상품')),
                ('ref_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='platform_ui.transaction', verbose_name='관련 거래')),
            ],
            options={
                'verbose_name': '재고 수불부',
                'verbose_name_plural': '입출고 이력',
            },
        ),
        migrations.AddField(
            model_name='inventory',
            name='tax_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='platform_ui.taxcode', verbose_name='과세 구분'),
        ),
    ]
