# Generated by Django 4.2.27 on 2026-02-04 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_ui', '0003_inbound_outbound_purchaseorder_salesorder'),
        ('platform_ui', '0008_auditlog_forecastrun_partner_posrawsales_taxcode_and_more'),
    ]

    operations = [
    ]
