# Generated by Django 4.2.27 on 2026-02-06 02:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('platform_ui', '0009_merge_20260204_2201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminconfig',
            options={'verbose_name': '관리자 환경 설정', 'verbose_name_plural': '관리자 설정'},
        ),
        migrations.AlterModelOptions(
            name='communitypost',
            options={'verbose_name': '커뮤니티 게시글', 'verbose_name_plural': '커뮤니티 관리'},
        ),
        migrations.AlterModelOptions(
            name='consultation',
            options={'verbose_name': 'AI 상담 내역', 'verbose_name_plural': 'AI 상담 로그'},
        ),
        migrations.AlterModelOptions(
            name='localevent',
            options={'verbose_name': '지역 행사 정보', 'verbose_name_plural': '지역 행사 및 이벤트'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '수주/발주 요청', 'verbose_name_plural': '수주/발주 관리'},
        ),
        migrations.AlterModelOptions(
            name='ownersentiment',
            options={'verbose_name': '점주 심리 상태', 'verbose_name_plural': '점주 심리 로그'},
        ),
        migrations.AlterModelOptions(
            name='weather',
            options={'verbose_name': '날씨 정보', 'verbose_name_plural': '날씨 데이터'},
        ),
        migrations.AddField(
            model_name='inventory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='상품 이미지'),
        ),
        migrations.AlterField(
            model_name='adminconfig',
            name='key',
            field=models.CharField(default='admin', max_length=50, verbose_name='설정 키'),
        ),
        migrations.AlterField(
            model_name='adminconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='author',
            field=models.CharField(max_length=100, verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='content',
            field=models.TextField(verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='작성일'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='answer',
            field=models.TextField(blank=True, verbose_name='AI 답변'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='접수일'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='question',
            field=models.TextField(verbose_name='질문 내용'),
        ),
        migrations.AlterField(
            model_name='localevent',
            name='date',
            field=models.DateField(verbose_name='일시'),
        ),
        migrations.AlterField(
            model_name='localevent',
            name='impact_level',
            field=models.CharField(max_length=50, verbose_name='영향도'),
        ),
        migrations.AlterField(
            model_name='localevent',
            name='name',
            field=models.CharField(max_length=200, verbose_name='행사명'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='접수 일시'),
        ),
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platform_ui.inventory', verbose_name='대상 품목'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', '대기'), ('COMPLETED', '완료'), ('CANCELLED', '취소')], default='PENDING', max_length=20, verbose_name='상태'),
        ),
        migrations.AlterField(
            model_name='ownersentiment',
            name='cheer_message',
            field=models.TextField(verbose_name='응원 메시지'),
        ),
        migrations.AlterField(
            model_name='ownersentiment',
            name='mood_score',
            field=models.IntegerField(default=5, verbose_name='기분 점수'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='condition',
            field=models.CharField(max_length=50, verbose_name='기상 상태'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='날짜'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='temperature',
            field=models.FloatField(verbose_name='기온'),
        ),
    ]
