# Generated by Django 4.2.27 on 2026-02-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_ui', '0010_alter_adminconfig_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='product_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='상품명'),
        ),
        migrations.AddField(
            model_name='order',
            name='product_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='상품명'),
        ),
        migrations.AddField(
            model_name='positemmap',
            name='product_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='상품명'),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='product_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='상품명'),
        ),
    ]
