# Generated by Django 4.2.28 on 2026-02-09 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_ui', '0011_inventorymovement_product_name_order_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='product_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='상품명'),
        ),
    ]
