# Generated by Django 4.2.28 on 2026-02-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_ui', '0012_delivery_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='is_managed',
            field=models.BooleanField(default=True, verbose_name='재고 관리 여부'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='sale_status',
            field=models.CharField(choices=[('ON_SALE', '판매중'), ('STOPPED', '판매중지'), ('OUT_OF_STOCK', '품절')], default='ON_SALE', max_length=20, verbose_name='판매 상태'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='최종 수정일'),
        ),
    ]
