# Generated by Django 6.0.1 on 2026-02-01 14:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='작성자')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='질문')),
                ('answer', models.TextField(blank=True, verbose_name='AI 답변')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailySales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True, verbose_name='날짜')),
                ('revenue', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='실매출')),
                ('predicted_revenue', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='예상매출')),
                ('weather_impact', models.CharField(blank=True, max_length=100, verbose_name='날씨 영향')),
                ('event_impact', models.CharField(blank=True, max_length=100, verbose_name='이벤트 영향')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100, verbose_name='상품명')),
                ('current_stock', models.IntegerField(verbose_name='현재 재고')),
                ('optimal_stock', models.IntegerField(verbose_name='적정 재고')),
                ('status', models.CharField(choices=[('GOOD', '적정'), ('LOW', '부족'), ('OVER', '과잉')], default='GOOD', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LocalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='이벤트명')),
                ('date', models.DateField(verbose_name='날짜')),
                ('impact_level', models.CharField(max_length=50, verbose_name='매출 영향도')),
            ],
        ),
        migrations.CreateModel(
            name='OwnerSentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('mood_score', models.IntegerField(default=5, verbose_name='기분 점수 (1-10)')),
                ('cheer_message', models.TextField(verbose_name='응원 메시지')),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='날짜')),
                ('condition', models.CharField(max_length=50, verbose_name='날씨 상태')),
                ('temperature', models.FloatField(verbose_name='온도')),
            ],
        ),
    ]
