# Generated by Django 4.2.27 on 2026-02-03 08:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('platform_ui', '0005_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminconfig',
            name='master_key',
        ),
        migrations.AddField(
            model_name='dailysales',
            name='item_name',
            field=models.CharField(default='General', max_length=200, verbose_name='상품명'),
        ),
        migrations.AlterField(
            model_name='dailysales',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='날짜'),
        ),
        migrations.AlterUniqueTogether(
            name='dailysales',
            unique_together={('date', 'item_name')},
        ),
    ]
